export type Church = {
  _id?: string;
  name: string;
  denomination: string;
  description: string;
  address: string;
  state: string;
  city: string;
  pastorName: string;
  pastorEmail: string;
  pastorPhone: string;
  contactEmail: string;
  contactPhone: string;
  services: [string, ...string[]];
  image: string;
  latitude?: number;
  longitude?: number;
  isFeatured?: boolean;
  featuredUntil?: Date;
  paymentStatus?: "pending" | "completed" | "failed";
  stripeSessionId?: string;
  step: number;
  status: "published" | "draft" | "archived";
  slug?: string;
  createdBy?: string;
  createdAt?: Date;
  updatedAt?: Date;
};
