export type Event = {
  _id: string;
  church: string;
  title: string;
  slug: string;
  address?: string;
  city?: string;
  state?: string;
  date: string;
  time: string;
  description: string;
  image: string;
  featured: boolean;
  step: number;
  status: "draft" | "published";
  featuredUntil?: Date;
  paymentStatus?: "pending" | "completed" | "failed";
  stripeSessionId?: string;
  createdAt: Date;
  updatedAt: Date;
  organizer?: string;
};
